apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    type: frontend
  namespace: dev
spec:
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
          ports:
            - containerPort: 80
  replicas: 4
