kind: Service
apiVersion: v1
metadata:
  name: frontend
  labels:
    type: frontend
  namespace: dev
spec:
  selector:
    type: frontend
  type: NodePort
  ports:
    - name: frontend-port
      port: 80
      targetPort: 80
      nodePort: 30009
