apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
spec:
  selector:
    matchLabels:
      app: hotrod
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:

        - image: pablords/aiops-telemetry:latest
          name:  vivo-aiops-telemetry
          imagePullPolicy: Always
          env:
            - name: JAEGER_HOST_AGENT
              value: localhost
            - name: JAEGER_AGENT_PORT
              value: "6832"
          ports:
            - containerPort: 3000
              name: api-port
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m

        - image: jaegertracing/jaeger-agent:1.38
          name: jaeger-agent
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
          args: 
            [ "--reporter.grpc.host-port=jaeger-colector-0.jaeger-colector-service.default.svc.cluster.local:14250,jaeger-colector-1.jaeger-colector-service.default.svc.cluster.local:14250,jaeger-colector-2.jaeger-colector-service.default.svc.cluster.local:14250" ]
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m


---

apiVersion: v1
kind: Service
metadata:
  name: hotrod-service
  labels:
    app: hotrod
spec:
  type: LoadBalancer
  #loadBalancerIP: 23.99.177.90
  ports:
  
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: api-port

  selector:
    app: hotrod

