apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hotrod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hotrod
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 100Mi
