apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hotrod-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hotrod
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50