---
# tasks file for ubuntu
- name: Remove docker "Uninstall old versions" package
  apt:
    name:
      - docker
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  when: ansible_distribution == 'Ubuntu'

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: latest
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Create "docker" group
  group:
    name: "{{ docker_group }}"
    state: present
  tags:
    - docker

# sudo usermod -aG docker ubuntu
- name: Add remote "ubuntu" user to "docker" group
  user:
    name: "{{ remote_user }}"
    group: "{{ docker_group }}"
    append: yes
  tags:
    - docker

