apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jenkins
  namespace: devops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jenkins
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50