apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jenkins
  namespace: devops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jenkins
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50