- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl

- name: delete kubelet if exists
  shell: sudo rm -rf /etc/default/kubelet

- name: Configure node ip
  lineinfile:
    create: yes
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ansible_eth1.ipv4.address}}
  when: ansible_nodename ==  "master"

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted

- name: config cgGroup Docker
  shell: |
    rm -rf /etc/docker/daemon.json
    touch /etc/docker/daemon.json
    echo '{ "exec-opts": ["native.cgroupdriver=systemd"] }' >> /etc/docker/daemon.json

- name: Restart Docker
  service:
    name: docker
    daemon_reload: yes
    state: restarted

- name: reset kubeadm
  command: sudo kubeadm reset -f

- name: remove /etc/containerd/config.toml (CORRIGE ERRO KUBEADM INIT)
  shell: |
    sudo rm /etc/containerd/config.toml
    systemctl restart containerd

- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address={{ ansible_eth1.ipv4.address }} --apiserver-cert-extra-sans={{ ansible_eth1.ipv4.address }}  --node-name k8s-master --pod-network-cidr={{ ansible_eth1.ipv4.network }}/16
  when: ansible_nodename ==  "master"

- name: delete if exists kubeConfig
  shell: rm -rf /home/vagrant/.kube

- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
    - sudo mkdir -p /home/vagrant/.kube
    - sudo cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - sudo chown vagrant:vagrant /home/vagrant/.kube/config

- name: Install kube-router pod network
  become: false
  command: kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"


- name: Install MetalLB
  become: false
  command: "{{ item }}"
  with_items:
    - kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/namespace.yaml 
    - kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml

- name: Configure MetalLB
  become: false
  command: kubectl apply -f /home/vagrant/shared/k8s/config/metallb/main.yml

- name: Configure Ingress NGINX
  become: false
  command: kubectl apply -k /home/vagrant/shared/k8s/config/ingress/


- name: install helm
  shell: |
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh