apiVersion: v1
kind: Service
metadata:
  name: app-teste
  namespace: app-teste
  labels:
    app: app-teste
spec:
  type: {{.Values.service.type}}
  ports:
    - protocol: TCP
      port: 8081 #porta POD
      targetPort: {{.Values.service.port}} #porta CONTAINER
      #nodePort: 30005
  selector:
    app: app-teste
    tier: frontend


---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-teste
  namespace: app-teste
  labels:
    app: app-teste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-teste
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app-teste
        tier: frontend
    spec:
      containers:
        - image: {{ .Values.image.name }}
          name: app-teste
          resources:
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql
            - name: WORDPRESS_DB_PASSWORD
              value: "123456"
          ports:
            - containerPort: 80
              name: app-teste
