---
# tasks file for ubuntu
- name: Remove docker "Uninstall old versions" package
  apt:
    name:
      - docker
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  when: ansible_distribution == 'Ubuntu'

- name: Add Docker’s official GPG key
  ansible.builtin.shell: |
    sudo rm -rf /usr/share/keyrings/docker-archive-keyring.gpg 
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  when: ansible_distribution == 'Ubuntu'

- name: Add Docker Repository
  ansible.builtin.shell: |
    sudo rm -rf /etc/apt/sources.list.d/docker.list
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: ansible_distribution == 'Ubuntu'

- name: Install Docker Engine
  ansible.builtin.shell: | 
    sudo apt-get update
    sudo apt-get install docker-ce docker-ce-cli containerd.io
  when: ansible_distribution == 'Ubuntu'

- name: Create "docker" group
  group:
    name: "{{ docker_group }}"
    state: present
  tags:
    - docker

# sudo usermod -aG docker ubuntu
- name: Add remote "ubuntu" user to "docker" group
  user:
    name: "{{ remote_user }}"
    group: "{{ docker_group }}"
    append: yes
  tags:
    - docker

