all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: vagrant
    ansible_ssh_pass: vagrant



masters:
  hosts:
    master:
      ansible_host: 192.168.56.10 
      ansible_ssh_private_key_file: /vagrant/.vagrant/machines/master/virtualbox/private_key

nodes:
  hosts:
    node1:
      ansible_host: 192.168.56.21
      ansible_ssh_private_key_file: /vagrant/.vagrant/machines/node1/virtualbox/private_key
    node2:
      ansible_host: 192.168.56.22
      ansible_ssh_private_key_file: /vagrant/.vagrant/machines/node2/virtualbox/private_key

